language: node_js
node_js:
- 10
- 9
- 8
branches:
  except:
  - gh-pages
  - l10n_develop
addons:
  apt:
    packages:
    - xvfb
  chrome: stable
  sonarcloud:
    organization: '01100010011001010110010101110000'
    token:
      secure: xe7nM1sgP+0z4ZzgfrFh7RlHQWVtFcziWl0DlMfEOl9W/8OzEUlqbAcP0HqNynAv4CEuHUdodd6szupOvSmizHUcsaW9aeDcd0n4QnO4L+Ce4Z4n8FwZDsHHGIXB8/rIqmDhIVlXJ6RM65ScM6sP+pBxjwCMKC1JvH9B9jHbhhRNLDIDjouWYt/dp3de5bBtCPMVXdM81iWJAe2/qobwhkOEeMmcEKHJnFgw/hLa4LW4ra1ciz56Xe6PNP1qcGGBCQUafB37pSVZKkjjd48YQDPni8DWJGcYmvb45Y4RK9mCDvndqUTJ6HuN71T1GqU/beuKYrdFAGApC+BpYMgSjxxvwHh+3dXFN9CTLBRowkVseqp8kkP4NBp2B7yRew1LVjX/AihhsKMecfK8aMbDyNZY0FJqQPqvUwZ3OlHDp1ayEfxQWaiuevRSGl6/GD7ErCn5l2y5X9iIFt7m24lEEatLJfqa/a7p03vn61V4DjZPR7xA8Q8Po1G1OYEPNg/MbR+ownIjZGZlSG9aOMefLoTxxyVaAgod2P96XRyYZ1cY+fwCZUZ9PeBjSrZTP71lDTBUiAGk3HMbXS6L+PNCeis6MowTwzNPyDJ/Fwzc9sIAurSZ0Pc+6yvofQrzewiMLLjEcPCl4mGXv8K9VTmKUDqSieCeB56+PXbEHTmkEZo=
env:
  global:
  - DISPLAY=:99
before_install:
- rm -rf node_modules
before_script:
- npm install grunt-cli -g
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- npm test
- npm run frisby
- NODE_ENV=ctf npm run protractor
- sonar-scanner -X
after_success:
- "./node_modules/.bin/lcov-result-merger 'build/reports/coverage/*/lcov.info' 'build/reports/coverage/lcov_merged.info'"
- "./node_modules/.bin/codeclimate-test-reporter < ./build/reports/coverage/lcov_merged.info"
notifications:
  webhooks:
    secure: L+X7UC9wCd//tlJEkO0TgiJYaQamy42HM9AEDO6wKvMQ90mkeDmD+YVEE61F9B/wzUR74oAqB0dgjG5SC7+Aal+DkXmPgpJ67QPkq0TIXbiSo/Td6T6HRsfa99t7AevHd0HyNOfj5BK7lftm/5q5PAh3D/pS1fvURgqpCLimFgkllLfoDoVWSjtDRr3P/RKjHlXFZaVr/xUgMxeQVCi5PbYbmNFg3+mRoOR1nm0a9SWKln4nvnSSHfBJXX+gHnTKzif6LGfG0vGPSCVnS1xUKbamJJFUc/5EHLdJb74stMWDzZNOb+cumMEuzEnZSph120pjiB69WFhWviOr6IPrSAnquRvXtHNjeB1aJPsMnPrKamNyY9w9ORcFC8bErzUrC6XU0LPBcq0X0J0ZYFVmwaw+z2vxe6nsouIc+yWavxGphE6/sBj6QLj6OhHwI8jq9yHB98hky0ydMjGqju8dcalifyh4PdPaSJTqz2q8IJL4gsfvB1nSUCtKf8oNzbCxjeK3P6PoKT0LNVpyjumiNNRTyPVy+B80YpDq5HmexB9jLkAsrafYXD87kPydmbY2r38hpF4wKshuUlB6tqTBab9pdssuK0kFWgwsi4roUJitAFX/SdB8hKT1PCa/xrjrsX8MaN917kZ141mxtUOEW6EDvB3CMikG4EFnC3BGHEc=
