language: node_js
node_js:
- 10
- 9
- 8
branches:
  except:
  - gh-pages
  - l10n_develop
addons:
  apt:
    packages:
    - xvfb
  chrome: stable
  sonarcloud:
    projectKey: 01100010011001010110010101110000_juice-shop
    sources: "."
    organization: "01100010011001010110010101110000"
    token: $token
env:
  global:
  - DISPLAY=:99
  - SONAR_TOKEN=$token
before_install:
- rm -rf node_modules
before_script:
- npm install grunt-cli -g
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- sonar-scanner
  #- npm test
  #- npm run frisby
  #- NODE_ENV=ctf npm run protractor
after_success:
- "./node_modules/.bin/lcov-result-merger 'build/reports/coverage/*/lcov.info' 'build/reports/coverage/lcov_merged.info'"
- "./node_modules/.bin/codeclimate-test-reporter < ./build/reports/coverage/lcov_merged.info"
notifications:
  webhooks:
    secure: L+X7UC9wCd//tlJEkO0TgiJYaQamy42HM9AEDO6wKvMQ90mkeDmD+YVEE61F9B/wzUR74oAqB0dgjG5SC7+Aal+DkXmPgpJ67QPkq0TIXbiSo/Td6T6HRsfa99t7AevHd0HyNOfj5BK7lftm/5q5PAh3D/pS1fvURgqpCLimFgkllLfoDoVWSjtDRr3P/RKjHlXFZaVr/xUgMxeQVCi5PbYbmNFg3+mRoOR1nm0a9SWKln4nvnSSHfBJXX+gHnTKzif6LGfG0vGPSCVnS1xUKbamJJFUc/5EHLdJb74stMWDzZNOb+cumMEuzEnZSph120pjiB69WFhWviOr6IPrSAnquRvXtHNjeB1aJPsMnPrKamNyY9w9ORcFC8bErzUrC6XU0LPBcq0X0J0ZYFVmwaw+z2vxe6nsouIc+yWavxGphE6/sBj6QLj6OhHwI8jq9yHB98hky0ydMjGqju8dcalifyh4PdPaSJTqz2q8IJL4gsfvB1nSUCtKf8oNzbCxjeK3P6PoKT0LNVpyjumiNNRTyPVy+B80YpDq5HmexB9jLkAsrafYXD87kPydmbY2r38hpF4wKshuUlB6tqTBab9pdssuK0kFWgwsi4roUJitAFX/SdB8hKT1PCa/xrjrsX8MaN917kZ141mxtUOEW6EDvB3CMikG4EFnC3BGHEc=
